In [1]:
import numpy as np


## ndarray

In [2]:
# 创建数组 array
data1 = [6,7,8,0,1]
np.array(data1) # 创建一维数组

array([6, 7, 8, 0, 1])

In [3]:
# 创建多维数组
data2 = [[1,2,3,4,5], [6,7,8,9,0]]
arr1 = np.array(data2)
print(arr1)

# dtype, 数据类型
arr1.dtype
# shape 属性
arr1.shape


[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [4]:
arr2 = np.array(data2, dtype=np.int64)
print(arr2)
print(arr2.dtype)

[[1 2 3 4 5]
 [6 7 8 9 0]]
int64


In [5]:
data3 = [6,7.5,8,5,0,1]
arr3 = np.array(data3)
print(arr3)
print(arr3.dtype)

[6.  7.5 8.  5.  0.  1. ]
float64


In [6]:
# astype 类型转换
arr3.astype(np.int64)

array([6, 7, 8, 5, 0, 1])

In [7]:
# ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
# 数组和标量之间的运算
nd = np.array([1,2,3,4])
print(nd*nd)

[ 1  4  9 16]


## 基本的索引和切片

In [11]:
# arange range函数的数组版
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nd1 = np.arange(1, 20, 2)
print(nd1)

[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
nd1[5]

11

In [14]:
nd1[2:4] = 10
print(nd1)

[ 1  3 10 10  9 11 13 15 17 19]


In [15]:
# 多维数组
data2 = [[1,2,3,4], [5,6,7,8]]
nd = np.array(data2)
print(nd)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
nd[0,3]

4

## 花式索引

In [17]:
nd = np.arange(32)
print(nd)

# reshape
nd1 = np.reshape(nd, (8, 4))
print(nd1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


## 通用函数 ufunc

In [22]:
arr=np.arange(10)
print(arr)
np.sqrt(arr)
B=np.arange(3)
print(B)

C=np.array([3,1,4])
print(C)

np.add(B,C)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[3 1 4]


array([3, 2, 6])

## 常用的数学统计方法

In [33]:
arr=np.random.randn(9)
print(arr)

print(arr.min())

print(arr.max())

print(arr.mean())

arr.sort()
print(arr)



[ 0.31518444 -1.09383632  0.61804404 -0.03358234 -1.41998445 -1.48399797
  0.31159322  0.54771241 -0.15542433]
-1.4839979718917757
0.6180440419744493
-0.2660323670892673
[-1.48399797 -1.41998445 -1.09383632 -0.15542433 -0.03358234  0.31159322
  0.31518444  0.54771241  0.61804404]
[[-0.60551478 -0.01842496 -2.11460069]
 [-1.04547147  0.09355893 -1.11196529]
 [ 1.63364505 -0.40187847 -0.52676532]
 [-0.24116654  0.49157713  0.05839818]
 [-0.09055112  0.82050305 -0.03593512]]


In [39]:
arr1 = np.random.randn(5,3)
print(arr1)

print(arr1.min())
print(arr1.max())

arr1.sort(axis=0)
print(arr1)
arr1.sort()
print(arr1)


[[ 2.20394996  1.11883296  1.02030788]
 [-0.29088146  0.45055841 -0.03205847]
 [ 0.78807934  1.83152248  1.1874307 ]
 [ 1.15687926 -0.23230042  0.60272109]
 [-1.2443073   2.23350301  0.96423264]]
-1.2443073045997712
2.233503008569318
[[-1.2443073  -0.23230042 -0.03205847]
 [-0.29088146  0.45055841  0.60272109]
 [ 0.78807934  1.11883296  0.96423264]
 [ 1.15687926  1.83152248  1.02030788]
 [ 2.20394996  2.23350301  1.1874307 ]]
[[-1.2443073  -0.23230042 -0.03205847]
 [-0.29088146  0.45055841  0.60272109]
 [ 0.78807934  0.96423264  1.11883296]
 [ 1.02030788  1.15687926  1.83152248]
 [ 1.1874307   2.20394996  2.23350301]]


##  矩阵乘法 求逆及随机数的生成

In [41]:
x = np.array([[1,3,4], [4,5,6]])
print(x)

y = np.array([[6,23], [-1, 7], [8,9]])
print(y)

x.dot(y)

[[1 3 4]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]


array([[ 35,  80],
       [ 67, 181]])

In [43]:
from numpy.linalg import inv
m=np.array([[4,2], [3,1]])
print(m)
inv(m)

[[4 2]
 [3 1]]


array([[-0.5,  1. ],
       [ 1.5, -2. ]])

In [45]:

from numpy import random

rArray = random.normal(size=(4,4))
print(rArray)

[[ 1.18406982 -0.87030408  1.70815714  0.08824941]
 [-0.6802097   0.6191346   0.84934452 -0.41623142]
 [-0.66398469  2.0812474   0.19893491  0.39870826]
 [-1.46238221 -0.56242182 -1.94971067  0.26140242]]
