In [1]:
import numpy as np


## ndarray

In [2]:
# 创建数组 array
data1 = [6,7,8,0,1]
np.array(data1) # 创建一维数组

array([6, 7, 8, 0, 1])

In [5]:
# 创建多维数组
data2 = [[1,2,3,4,5], [6,7,8,9,0]]
arr1 = np.array(data2)
print(arr1)

# dtype, 数据类型
arr1.dtype
# shape 属性
arr1.shape


[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [7]:
arr2 = np.array(data2, dtype=np.int64)
print(arr2)
print(arr2.dtype)

[[1 2 3 4 5]
 [6 7 8 9 0]]
int64


In [9]:
data3 = [6,7.5,8,5,0,1]
arr3 = np.array(data3)
print(arr3)
print(arr3.dtype)

[6.  7.5 8.  5.  0.  1. ]
float64


In [10]:
# astype 类型转换
arr3.astype(np.int64)

array([6, 7, 8, 5, 0, 1])

In [11]:
# ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# 数组和标量之间的运算
nd = np.array([1,2,3,4])
print(nd*nd)

[ 1  4  9 16]


## 基本的索引和切片

In [20]:
# arange range函数的数组版
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nd1 = np.arange(1, 20, 2)
print(nd1)

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
nd1[5]

11

In [19]:
nd1[2:4] = 10
print(nd1)

[ 1  3 10 10  9 11 13 15 17 19]


In [21]:
# 多维数组
data2 = [[1,2,3,4], [5,6,7,8]]
nd = np.array(data2)
print(nd)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
nd[0,3]

4

## 花式索引

In [26]:
nd = np.arange(32)
print(nd)

# reshape
nd1 = np.reshape(nd, (8, 4))
print(nd1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
