In [1]:
import numpy as np

np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
data=np.arange(16).reshape((4,4))
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
df DataFrame(data=data, index=['a','b','c','d'], columns=['one','two','three','four'])
df


SyntaxError: invalid syntax (<ipython-input-4-08ad755a752b>, line 1)